"""Hand-written routing messages for the two intents with no authentic chat-style source.

Written for the routing gold set (see eval_routing.py); reviewed by the project owner before use.
"""

FIND_LAWYER = [
    "I need a lawyer for my divorce case in Pune",
    "Can you suggest a good criminal lawyer in Delhi?",
    "Looking for an advocate who handles property disputes in Hyderabad",
    "please recommend a family lawyer near Andheri",
    "Who is the best lawyer for cheque bounce cases in Chennai?",
    "I want to hire a lawyer for my father's bail hearing",
    "Need an experienced consumer court advocate in Kolkata",
    "Find me a lawyer who speaks Tamil for a land case",
    "Can you connect me with a labour law specialist? My company fired me illegally",
    "Mujhe ek acha vakeel chahiye property case ke liye, Lucknow mein",
    "any good advocate in jaipur for 498a case??",
    "I am looking for a woman lawyer for a domestic violence matter",
    "Suggest a lawyer for RERA complaint against my builder in Noida",
    "Which lawyers on your platform handle cyber crime cases?",
    "I need legal representation in the Bombay High Court for a writ petition",
    "Recommend an affordable lawyer for a small civil suit",
    "Is there a lawyer available who does online consultations for NRI property issues?",
    "Need a corporate lawyer to review my startup's shareholder agreement",
    "Can I book an appointment with a tax lawyer this week?",
    "Help me find a good immigration lawyer",
    "I want to talk to a lawyer about my mother's will, who should I contact",
    "looking for lawyer in bangalore urgent",
    "Show me lawyers who specialise in motor accident claims",
    "I need an advocate to file an anticipatory bail application in Gurgaon",
    "Who can represent me in a consumer forum case against an airline?",
    "Please find a lawyer in Ahmedabad experienced with GST disputes",
    "need a vakil for court marriage formalities",
    "Recommend a trademark lawyer for registering my brand",
    "Can you suggest a lawyer with a high success rate in custody cases?",
    "I'd like to consult a senior advocate about an appeal in the Supreme Court",
    "Which lawyer should I approach for a partition suit in Kerala?",
    "Find a criminal defence advocate who can take a case in Patna",
    "My brother got arrested, we need a lawyer immediately in Indore",
    "Can you list some employment lawyers in Mumbai with their fees?",
    "I want a lawyer to send a legal notice to my tenant",
    "Do you have any lawyers for medical negligence cases?",
    "Suggest a good lawyer for mutual consent divorce, budget is limited",
    "Need an advocate who handles SARFAESI and bank auction matters",
    "Who is a reliable lawyer for property registration in Chandigarh?",
    "please help me find lawyer for my uncle's land dispute in village near Nagpur",
    "I'm looking for a lawyer who handles defamation cases",
    "Get me a lawyer for an insurance claim rejection",
    "Recommend a lawyer to draft my will",
    "kya aap koi criminal lawyer suggest kar sakte ho Bhopal mein",
    "Need a lawyer for a cheating case filed against me",
    "I need someone to represent me at the family court next Monday",
    "Can I hire one of your lawyers for a POCSO case?",
    "Looking for an advocate for a service matter at the CAT",
    "Find lawyers near me who handle eviction of tenants",
    "Which advocate should I hire to fight a false dowry case?",
    "I want to book a consultation with a property lawyer",
    "Can you recommend a lawyer for intellectual property infringement?",
    "Need an arbitration lawyer for a commercial contract dispute",
    "I need a lawyer who can handle a case in both Delhi and Haryana courts",
    "suggest some good lawyers for maintenance case under 125",
    "Who are the top rated lawyers on this site for civil cases?",
    "Help me find an advocate to challenge a traffic challan in court",
    "I want a lawyer for adoption paperwork",
    "Need a lawyer urgently, police are refusing to register my FIR",
    "Recommend an NRI-friendly lawyer for selling my flat in Pune",
    "Is there any lawyer available for a free legal aid consultation?",
    "I need a lawyer for my company's insolvency proceedings before NCLT",
    "Please suggest an advocate for a land acquisition compensation case",
    "Find a lawyer in Guwahati who handles family matters",
    "can u find me lawyer for my sisters divorce, she lives in coimbatore",
    "I'm searching for a criminal lawyer with experience in NDPS cases",
    "Which lawyer can help me with a succession certificate?",
    "Need a good lawyer to defend a defamation suit against my newspaper",
    "Suggest a lawyer to handle my visa refusal appeal",
    "I want to engage a lawyer for a consumer case about a defective car",
    "Can you show me lawyers available tomorrow for a phone consultation?",
    "Recommend a lawyer for a builder delay case in Gurugram",
    "I need an advocate for a bail matter in Sessions Court Thane",
    "Find me a lawyer to file a RTI appeal",
    "Looking for a lawyer for my mother's pension dispute with the government",
    "i need lawyer who handle cyber fraud case where i lost 2 lakh",
    "Which of your lawyers handles cases in the Madras High Court?",
]

DOCUMENT_ANALYSIS = [
    "Please review this rent agreement I just uploaded",
    "Can you check if this sale deed has any problems?",
    "I've attached my employment offer letter, is the non-compete clause enforceable?",
    "What does this legal notice mean? I've uploaded it",
    "Check this affidavit for mistakes before I get it notarised",
    "Is this power of attorney valid for selling my flat?",
    "Summarise the attached court order in simple words",
    "Go through this FIR copy and tell me which sections are applied",
    "Review the will I uploaded and tell me if anything is missing",
    "Can you analyse this partnership deed for risky clauses?",
    "Here is the agreement to sell, does it protect me as the buyer?",
    "Please read this bail order and explain the conditions",
    "Is the stamp duty mentioned in this document correct?",
    "Check whether this lease deed needs registration",
    "I uploaded the chargesheet, what are the charges against my brother?",
    "Look at this notice from my landlord and tell me my options",
    "Does this contract have a termination clause? Please check the file",
    "Can you verify if this gift deed is properly executed?",
    "Explain the judgment I've attached, did we win or lose?",
    "Please check this NDA before I sign it",
    "what are the key points in this document",
    "Is this complaint under CrPC drafted properly? File attached",
    "Review my bail application draft for errors",
    "Tell me if this rental agreement favours the landlord too much",
    "I got this summons, please explain what it says",
    "Check this loan agreement for hidden charges",
    "Analyse this service agreement, is the payment clause fair?",
    "Does the uploaded sale deed mention all the boundaries correctly?",
    "Can you find any loopholes in this contract?",
    "Please go through this property document and tell me if the title is clear",
    "read this and tell me what i should do",
    "Is this divorce petition complete? I have uploaded the draft",
    "Check this employment bond, can they really make me pay 3 lakh?",
    "What are my obligations under this agreement?",
    "Kindly examine the attached legal notice and suggest a reply",
    "Please check if the witnesses on this will are sufficient",
    "Review this franchise agreement for unfair terms",
    "Is there anything wrong with this leave and licence agreement?",
    "I've uploaded the maintenance order, how much do I have to pay?",
    "Highlight the risky clauses in this vendor contract",
    "Is the arbitration clause in this document valid in India?",
    "Can you check this cheque bounce notice I received?",
    "Explain this court order in Hindi please",
    "Summarize this document",
    "Look through the attached chargesheet and list the evidence mentioned",
    "Does this rent agreement need a police verification clause?",
    "Check the uploaded consumer complaint before I file it",
    "Is this power of attorney revocable? See attached",
    "Tell me if this employment contract violates labour laws",
    "Please validate this sale agreement against the registration requirements",
    "I attached the notice from the bank under SARFAESI, what does it mean for me?",
    "Analyse this partnership deed, how are profits shared?",
    "Is this affidavit format acceptable for a name change?",
    "Check this agreement and tell me who bears the maintenance costs",
    "Go through my uploaded will draft and suggest improvements",
    "What does clause 7 in this document mean?",
    "can u check this doc and tell if its legally valid",
    "Is the indemnity clause in this contract too broad?",
    "Review the attached settlement agreement before mediation",
    "Please explain the conditions in this anticipatory bail order",
    "Check if this deed has the correct stamp paper value for Maharashtra",
    "I've uploaded my tenancy agreement, can my landlord increase rent mid-term?",
    "Read the judgment and tell me the grounds the court relied on",
    "Is this notice period clause in my offer letter enforceable?",
    "Look at this lease and tell me when it expires",
    "Can you check whether this agreement to sell has a penalty clause for delay?",
    "Please review this MOU between two companies",
    "Does this document prove ownership of the land?",
    "Check this FIR, is my name mentioned as an accused?",
    "Analyse the attached police complaint and tell me if it's strong enough",
    "Explain the terms of this loan sanction letter",
    "Tell me what is missing in this rent agreement",
    "I uploaded a court notice, when do I have to appear?",
    "Review this settlement deed between my siblings and me",
    "Is this contract one-sided? Please go through it",
    "Check this employment termination letter, was due process followed?",
    "Please check the attached builder-buyer agreement for RERA compliance",
    "what is this document about",
    "Verify whether this will is properly attested",
    "Compare this draft agreement with the one we signed last year and list the changes",
]
