"""
Keyword banks for the chatbot's zero-latency routing / domain-hint layer.

These frozensets are pure data consumed by the fast keyword matchers in
``app.chatbot`` (``_stage1_domain_check``, ``_infer_domain_hint``, etc.).
They live here so ``chatbot.py`` stays focused on control flow rather than
long literal blocks. No logic — imports must have no side effects.
"""

# ============================================================================
# Domain check (Legal vs Non-Legal) — Stage 1 fast pre-filter
# ============================================================================

# Non-legal patterns (casual conversation)
NON_LEGAL_PATTERNS = frozenset(
    [
        "my favorite",
        "my favourite",
        "i like",
        "i love",
        "favorite color",
        "favourite color",
        "best food",
        "favorite movie",
        "what is your",
        "how are you",
        "good morning",
        "good night",
        "hello",
        "hi there",
        "weather today",
        "tell me a joke",
        "sing a song",
        "who are you",
        "your name",
        "thank you",
        "thanks",
        "bye",
        "goodbye",
    ]
)

# Legal domain indicators
LEGAL_DOMAIN_KEYWORDS = frozenset(
    [
        "law",
        "legal",
        "court",
        "judge",
        "crime",
        "police",
        "lawyer",
        "attorney",
        "ipc",
        "crpc",
        "section",
        "act",
        "right",
        "constitution",
        "case",
        "fir",
        "bail",
        "arrest",
        "prosecution",
        "verdict",
        "judgment",
        "statute",
        "offence",
        "offense",
        "punishment",
        "penalty",
        "fine",
        "imprisonment",
        "contract",
        "agreement",
        "deed",
        "property",
        "tenant",
        "landlord",
        "divorce",
        "custody",
        "maintenance",
        "alimony",
        "will",
        "testament",
        "inheritance",
        "defamation",
        "fraud",
        "cheating",
        "theft",
        "robbery",
    ]
)

# Document validation keywords
VALIDATION_KEYWORDS = frozenset(
    [
        "validate",
        "validity",
        "check validity",
        "verify",
        "statutory compliance",
        "defects",
        "legal defects",
        "is this valid",
        "check compliance",
        "missing elements",
        "properly drafted",
        "drafting defects",
        "formal defects",
        "mandatory requirements",
        "stamp duty compliance",
        "review this document",
        "check this document",
        "is this correct",
        "is this proper",
    ]
)

# IPC/CrPC/Statute keywords (→ Crime RAG)
STATUTE_KEYWORDS = frozenset(
    [
        "ipc",
        "indian penal code",
        "crpc",
        "criminal procedure",
        "punishment",
        "imprisonment",
        "fine",
        "penalty",
        "forgery",
        "trespass",
        "assault",
        "threat",
        "intimidation",
        "fraud",
        "cheating",
        "theft",
        "robbery",
        "bribery",
        "cyber",
        "hacking",
        "identity theft",
        "money laundering",
        "defamation",
        "kidnapping",
        "murder",
        "hurt",
        "grievous",
        "it act",
        "information technology",
        "prevention of corruption",
        "poca",
        "pmla",
    ]
)

# Crime type keywords for multi-offense detection
CRIME_TYPE_KEYWORDS = frozenset(
    [
        "forgery",
        "forged",
        "trespass",
        "trespassed",
        "assault",
        "assaulted",
        "threat",
        "threatened",
        "bribe",
        "bribery",
        "fraud",
        "cyber",
        "identity theft",
        "launder",
        "laundering",
        "cheating",
        "theft",
        "robbery",
        "murder",
        "kidnapping",
        "extortion",
        "blackmail",
        "defamation",
        "harassment",
        "stalking",
        "dowry",
        "domestic violence",
    ]
)

# ============================================================================
# Domain keyword banks — sole remaining consumer is _infer_domain_hint
# ============================================================================

# Constitutional & fundamental rights keywords (→ Indian Kanoon)
CONSTITUTIONAL_KEYWORDS = frozenset(
    [
        "article",
        "fundamental right",
        "fundamental rights",
        "constitution",
        "constitutional",
        "amendment",
        "basic structure",
        "parliament",
        "legislature",
        "writ",
        "habeas corpus",
        "mandamus",
        "certiorari",
        "prohibition",
        "quo warranto",
        "right to privacy",
        "right to life",
        "right to equality",
        "free speech",
        "freedom of speech",
        "freedom of expression",
        "public order",
        "reasonable restriction",
        "directive principles",
        "dpsp",
        "preamble",
        "federalism",
        "president",
        "governor",
        "president's rule",
        "article 356",
        "article 19",
        "article 21",
        "article 14",
        "article 32",
        "article 226",
        "article 370",
        "article 370",
        "ninth schedule",
        "seventh schedule",
        "union list",
        "concurrent list",
        "state list",
        "surveillance",
        "proportionality",
        "puttaswamy",
        "kesavananda",
        "minerva mills",
        "maneka gandhi",
        "golaknath",
    ]
)

# Civil / Contract law keywords (→ Indian Kanoon)
CIVIL_LAW_KEYWORDS = frozenset(
    [
        "contract",
        "agreement",
        "enforceable",
        "void",
        "voidable",
        "consideration",
        "breach",
        "specific performance",
        "damages",
        "indemnity",
        "guarantee",
        "coercion",
        "undue influence",
        "misrepresentation",
        "mistake",
        "frustration",
        "force majeure",
        "non-compete",
        "restraint of trade",
        "liquidated damages",
        "injunction",
        "arbitration",
        "mediation",
        "consumer protection",
        "tort",
        "negligence",
        "defamation",
        "nuisance",
        "indian contract act",
        "section 10",
        "section 23",
        "section 25",
        "section 27",
        "section 56",
        "section 73",
        "section 74",
        "sale of goods",
        "negotiable instruments",
        "partnership",
        "llp",
        "oral agreement",
        "oral contract",
        "stamp duty",
        "registration",
        "admissible",
        "admissibility",
        "evidence",
        "section 65b",
        "electronic evidence",
        "digital evidence",
        "whatsapp",
        "electronic record",
    ]
)

# Property law keywords (→ Indian Kanoon)
PROPERTY_LAW_KEYWORDS = frozenset(
    [
        "property",
        "ancestral property",
        "coparcenary",
        "partition",
        "sale deed",
        "gift deed",
        "will",
        "testament",
        "succession",
        "inheritance",
        "legal heir",
        "legal heirs",
        "hindu succession",
        "transfer of property",
        "easement",
        "mortgage",
        "lease",
        "tenancy",
        "tenant",
        "landlord",
        "rent control",
        "eviction",
        "encumbrance",
        "benami",
        "rera",
        "real estate",
        "mutation",
        "land revenue",
        "stridhan",
        "joint family",
        "huf",
    ]
)

# Family law keywords (→ Indian Kanoon)
FAMILY_LAW_KEYWORDS = frozenset(
    [
        "divorce",
        "custody",
        "maintenance",
        "alimony",
        "domestic violence",
        "dowry",
        "marriage",
        "matrimonial",
        "judicial separation",
        "mutual consent",
        "cruelty",
        "desertion",
        "restitution of conjugal rights",
        "live-in",
        "live in partner",
        "cohabitation",
        "hindu marriage act",
        "special marriage act",
        "muslim personal law",
        "guardianship",
        "adoption",
        "juvenile",
        "child marriage",
        "marital rape",
        "section 498a",
        "protection of women",
        "dv act",
    ]
)

# Technology & modern law keywords (→ Indian Kanoon)
TECH_LAW_KEYWORDS = frozenset(
    [
        "cryptocurrency",
        "crypto",
        "bitcoin",
        "blockchain",
        "artificial intelligence",
        "ai liability",
        "data protection",
        "personal data",
        "gdpr",
        "pdp bill",
        "dpdp",
        "social media",
        "online",
        "internet",
        "deepfake",
        "it act",
        "information technology act",
        "section 66a",
        "section 67",
        "section 43",
        "intermediary",
        "safe harbour",
        "takedown",
        "right to be forgotten",
        "aadhaar",
        "rbi",
        "fema",
        "pmla",
        "sebi",
    ]
)

# Criminal procedure & bail keywords (→ Crime RAG + Indian Kanoon)
CRIMINAL_PROCEDURE_KEYWORDS = frozenset(
    [
        "fir",
        "bail",
        "anticipatory bail",
        "regular bail",
        "quash",
        "quashing",
        "section 482",
        "section 438",
        "section 439",
        "section 154",
        "section 200",
        "section 320",
        "compoundable",
        "non-compoundable",
        "chargesheet",
        "investigation",
        "cognizable",
        "non-cognizable",
        "complainant",
        "withdrawal",
        "compound",
        "plea bargaining",
        "discharge",
        "acquittal",
        "conviction",
        "appeal",
        "revision",
        "review",
        "habeas corpus",
        "remand",
        "police custody",
        "judicial custody",
        "bhajan lal",
    ]
)

# The only keyword signals treated as "strong, unambiguous criminal" for
# _infer_domain_hint — explicit section/procedure references, not generic
# crime-adjacent words. Deliberately narrow.
STRONG_CRIMINAL_SIGNAL_KEYWORDS = frozenset(
    [
        "which section",
        "what section",
        "applicable section",
        "sections apply",
        "ipc section",
        "crpc section",
        "under which",
        "punishable under",
        "punishment for",
        "penalty for",
        "imprisonment for",
        "fine for",
        "cognizable",
        "non-cognizable",
        "bailable",
        "non-bailable",
        "compoundable",
        "non-compoundable",
        "triable by",
        "investigation",
        "chargesheet",
        "fir for",
        "file fir",
        "police complaint",
    ]
)
