import { Lawyer } from '../App';

export const mockLawyers: Lawyer[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    specialty: 'Criminal Defense',
    experience: 15,
    rating: 4.9,
    hourlyRate: 350,
    location: 'New York, NY',
    bio: 'Experienced criminal defense attorney with a proven track record in white-collar crimes, DUI cases, and federal offenses.',
    cases: 450,
    successRate: 92,
    education: 'Harvard Law School, JD',
    languages: ['English', 'Spanish'],
    availability: 'Available this week',
  },
  {
    id: '2',
    name: 'David Chen',
    specialty: 'Family Law',
    experience: 12,
    rating: 4.8,
    hourlyRate: 275,
    location: 'Los Angeles, CA',
    bio: 'Compassionate family lawyer specializing in divorce, child custody, and adoption cases with a focus on mediation.',
    cases: 380,
    successRate: 88,
    education: 'Stanford Law School, JD',
    languages: ['English', 'Mandarin'],
    availability: 'Available next week',
  },
  {
    id: '3',
    name: 'Jennifer Rodriguez',
    specialty: 'Business & Corporate Law',
    experience: 18,
    rating: 4.9,
    hourlyRate: 425,
    location: 'Chicago, IL',
    bio: 'Corporate attorney advising startups and established companies on contracts, mergers, acquisitions, and compliance.',
    cases: 520,
    successRate: 95,
    education: 'Yale Law School, JD',
    languages: ['English', 'Spanish', 'Portuguese'],
    availability: 'Limited availability',
  },
  {
    id: '4',
    name: 'Michael Thompson',
    specialty: 'Personal Injury',
    experience: 10,
    rating: 4.7,
    hourlyRate: 225,
    location: 'Houston, TX',
    bio: 'Dedicated personal injury lawyer fighting for victims of car accidents, workplace injuries, and medical malpractice.',
    cases: 310,
    successRate: 85,
    education: 'University of Texas Law School, JD',
    languages: ['English'],
    availability: 'Available this week',
  },
  {
    id: '5',
    name: 'Emily Watson',
    specialty: 'Real Estate Law',
    experience: 14,
    rating: 4.8,
    hourlyRate: 300,
    location: 'Miami, FL',
    bio: 'Real estate attorney handling residential and commercial transactions, landlord-tenant disputes, and zoning issues.',
    cases: 425,
    successRate: 91,
    education: 'Duke University School of Law, JD',
    languages: ['English', 'French'],
    availability: 'Available this week',
  },
  {
    id: '6',
    name: 'Robert Johnson',
    specialty: 'Immigration Law',
    experience: 16,
    rating: 4.9,
    hourlyRate: 280,
    location: 'San Francisco, CA',
    bio: 'Immigration attorney helping clients with visas, green cards, citizenship, and deportation defense cases.',
    cases: 490,
    successRate: 93,
    education: 'UC Berkeley School of Law, JD',
    languages: ['English', 'Spanish', 'Hindi'],
    availability: 'Available next week',
  },
  {
    id: '7',
    name: 'Amanda Foster',
    specialty: 'Intellectual Property',
    experience: 11,
    rating: 4.8,
    hourlyRate: 375,
    location: 'Seattle, WA',
    bio: 'IP attorney specializing in patents, trademarks, copyrights, and technology licensing for tech companies.',
    cases: 340,
    successRate: 90,
    education: 'Columbia Law School, JD',
    languages: ['English', 'German'],
    availability: 'Available this week',
  },
  {
    id: '8',
    name: 'James Martinez',
    specialty: 'Criminal Defense',
    experience: 9,
    rating: 4.6,
    hourlyRate: 200,
    location: 'Phoenix, AZ',
    bio: 'Aggressive criminal defense lawyer handling drug offenses, theft, assault, and juvenile cases.',
    cases: 275,
    successRate: 84,
    education: 'Arizona State University Law School, JD',
    languages: ['English', 'Spanish'],
    availability: 'Available this week',
  },
  {
    id: '9',
    name: 'Lisa Park',
    specialty: 'Employment Law',
    experience: 13,
    rating: 4.7,
    hourlyRate: 310,
    location: 'Boston, MA',
    bio: 'Employment attorney representing employees in discrimination, wrongful termination, and wage disputes.',
    cases: 395,
    successRate: 87,
    education: 'Boston University School of Law, JD',
    languages: ['English', 'Korean'],
    availability: 'Available next week',
  },
  {
    id: '10',
    name: 'Christopher Adams',
    specialty: 'Tax Law',
    experience: 20,
    rating: 4.9,
    hourlyRate: 400,
    location: 'Washington, DC',
    bio: 'Tax attorney with extensive experience in tax planning, IRS audits, and international tax compliance.',
    cases: 580,
    successRate: 94,
    education: 'Georgetown University Law Center, JD',
    languages: ['English'],
    availability: 'Limited availability',
  },
];
